/* 389
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"

Constraints:

    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.
*/

# include <stdio.h>

char findTheDifference(char* s, char* t) {
    char aux = 0;
    
    for(int i = 0; s[i] != '\0'; i++){ aux ^= s[i]; }
    for(int j = 0; t[j] != '\0'; j++){ aux ^= t[j]; }

    return aux;
}

int main(){
    char text1[] = "abcd";
    char text2[] = "abcde";

    char extra = findTheDifference(text1, text2);

    printf("Extra: %c", extra);

    return 0;
}

// 0 md of runtime.
// 8.82 MB of memory.
